### ISSUE TITLE
Symbology Edits

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#26]
Requested that the background remain neutral and the percentage bubbles be filled with the color. Use the same color gradient as is implemented. Percentage labels should generally be placed outside of the circles, though I think if the circle is extremely large, it could be within.

**Comment by horsburgh** [comment]
Let's be consistent and keep the labels outside.

**Comment by mauriel133** [comment]
Done

**Comment by AmberSJones** [comment]
Let's make the font on the percentage larger than the (n= xxx) font. Let's also center it in the box.

**Comment by mauriel133** [comment]
Douglas has also requested the 'not sure' bubbles to be colored with dark gray.

**Comment by mauriel133** [comment]
'Not sure' bubbles are now colored gray

**Comment by mauriel133** [comment]
The percentage font is now larger and the text is centered to the middle. The (n) label has been moved to the right and given a smaller font. 

Appending both text fields (so that they can be both centered at the middle) while preserving their font-sizes is a little more complicated and will be done later.

**Comment by AmberSJones** [comment]
Seems good to me. I'll close this issue and we can address any other symbology updates separately.
